-- Say Hi CTA section (after closing image)
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaEyebrowEn" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaEyebrowAr" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaTitleEn" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaTitleAr" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaBodyEn" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaBodyAr" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaButtonEn" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaButtonAr" TEXT;
ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "ctaWhatsappUrl" TEXT;
